### Post NULL

POST http://localhost:8080/artists
Content-Type: application/json

{
  "name": "Not Applicable"
}

### Post "BTS"

POST http://localhost:8080/artists
Content-Type: application/json

{
  "name": "BTS"
}

### Post "BLACKPINK"

POST http://localhost:8080/artists
Content-Type: application/json

{
  "name": "BLACKPINK"
}

### Post "LE SSERAFIM"

POST http://localhost:8080/artists
Content-Type: application/json

{
  "name": "LE SSERAFIM"
}

### Post "SEVENTEEN"

POST http://localhost:8080/artists
Content-Type: application/json

{
  "name": "SEVENTEEN"
}

### Get all the messages
GET http://localhost:8080/artists

### Get the message by its id
GET http://localhost:8080/artists/837950d6-9557-4184-a5d6-20459236d8ca

### Delete
DELETE http://localhost:8080/artists/ecaa2591-8883-41ec-a7a3-0531f1b5fd0f