
### Post
POST http://localhost:8080/items
Content-Type: application/json

{
  "gid": "5bcee200-f2d6-4b58-b288-22860a049690",
  "name": "Map of the Soul",
  "version": "7",
  "released": "2020",
  "price": "30"
}

### Update
PUT http://localhost:8080/items/cf379bec-6490-41aa-a7d8-6909f6f31bc9
Content-Type: application/json

{
  "gid": "924915c5-6401-48da-b800-7164f064bf86",
  "category": "Album",
  "name": "Unforgiven",
  "version": "1",
  "released": "2023",
  "price": "40"
}

### Get all the messages
GET http://localhost:8080/items
