spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: lina
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
cors:
  originPatterns: https://localhost:3000,https://localhost:8080